dashboard/dashboard/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("firstapp.urls")),  # Changed from "firstapp/" to ""
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/firstapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('weather_stats/', views.weather_stats, name='weather_stats'),
    path('pv_tool/', views.pv_tool, name='pv_tool'),
    path('energy_sim/', views.energy_sim, name='energy_sim'),
    path('rainwater/', views.rainwater, name='rainwater'),
    path('reset_epw/', views.reset_epw_session, name='reset_epw'),

]

dashboard/firstapp/models.py
from django.db import models

class EPWFile(models.Model):
    file = models.FileField(upload_to='epw_files/')
    uploaded_at = models.DateTimeField(auto_now_add=True)

dashboard/firstapp/forms.py
from django import forms
from .models import EPWFile

class EPWUploadForm(forms.ModelForm):
    class Meta:
        model = EPWFile
        fields = ['file']


class CatchmentAreaForm(forms.Form):
    width = forms.FloatField(min_value=0.0, required=True, widget=forms.NumberInput(attrs={'class': 'input-class', 'placeholder': 'Enter value...'}))
    length = forms.FloatField(min_value=0.0, required=True, widget=forms.NumberInput(attrs={'class': 'input-class', 'placeholder': 'Enter value...'}))
    catchment_area = forms.FloatField(required=False, widget=forms.NumberInput(attrs={'class': 'input-class', 'placeholder': ''}))

class PVToolForm(forms.Form):

    # Choices for the new dropdown
    ROOF_TYPES = (
        ('flat', 'Flat roof'),
        ('pitched', 'Pitched roof'),  
    )
    # Roof dimensions
    roof_length = forms.FloatField(label='Roof length (m):', min_value=0)
    roof_width = forms.FloatField(label='Roof width (m):', min_value=0)
    roof_type = forms.ChoiceField(choices=ROOF_TYPES, label='Roof Type')

    # PV properties
    module_efficiency = forms.FloatField(label='Module efficiency (%):', initial=18, min_value=0, max_value=100)
    pv_width = forms.FloatField(label='PV width (m):',initial=1.032, min_value=0)
    pv_height = forms.FloatField(label='PV height (m):',initial=1.872, min_value=0)
    inverter_efficiency = forms.FloatField(label='Inverter efficiency (%):', initial=96, min_value=0, max_value=100)
    other_losses = forms.FloatField(label='Other losses (%):', initial=14, min_value=0, max_value=100)

dashboard/firstapp/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
import re
from ladybug.futil import preparedir, nukedir
from .forms import EPWUploadForm
from .forms import CatchmentAreaForm
import openmeteo_requests, requests_cache
from retry_requests import retry
from .forms import PVToolForm
from .models import EPWFile
import json
from honeybee_energy.cli.simulate import simulate_model
from honeybee.typing import clean_ep_string
from honeybee_energy.run import to_openstudio_osw, run_osw, run_idf, output_energyplus_files
from honeybee_energy.result.generation import generation_data_from_sql, generation_summary_from_sql
from honeybee_energy.simulation.parameter import SimulationParameter
import math
# Import Ladybug Tools for analysis
from ladybug.epw import EPW
import sys
from honeybee.room import Room
from lbt_recipes.version import check_openstudio_version
from honeybee.model import Model
from ladybug_geometry.geometry3d import Vector3D, Point3D
from honeybee.shade import Shade
from honeybee_energy.generator.pv import PVProperties
#from honeybee_energy.run import RunEnergySimulation
from honeybee_vtk.model import Model as ModelVTK
import os
from django.conf import settings  # Add this import at the top of your views.py
#import openmeteo_requests
#import requests_cache
import pandas as pd
import shutil
#from retry_requests import retry

import numpy as np
import matplotlib
import seaborn as sns

import base64
matplotlib.use('Agg')  # Set the backend to 'Agg'
import matplotlib.pyplot as plt
from io import BytesIO


def home(request):
    if request.method == 'POST':
        form = EPWUploadForm(request.POST, request.FILES)
        if form.is_valid():
            epw_instance = form.save()  # Saves the EPW file instance
            epw_data = EPW(epw_instance.file.path)
            location = epw_data.location

            # Store necessary information in the session
            request.session['epw_file_id'] = epw_instance.id
            request.session['epw_file_location'] = f"{location.city}, {location.country}"
            request.session['epw_file_lat'] = location.latitude
            request.session['epw_file_long'] = location.longitude

            return redirect('weather_stats')
    else:
        form = EPWUploadForm()

    return render(request, 'firstapp/home.html', {'form': form})

def reset_epw_session(request):
    # List all session keys related to EPW data
    session_keys = ['epw_file_id', 'epw_file_location', 'epw_file_lat', 'epw_file_long']
    for key in session_keys:
        if key in request.session:
            del request.session[key]
    return redirect('home')


def extract_lat_long_from_epw(epw_file):
    # Implement the logic to extract latitude and longitude from the EPW file here
    # Placeholder return values
    return 52.52, 13.41

def weather_stats(request):
    context = {'active_page': 'weather_stats'}  # Initialize context with form and active_page
    epw_file_id = request.session.get('epw_file_id')

    if epw_file_id:
        try:
            epw_file_model = EPWFile.objects.get(id=epw_file_id)
            epw_file_path = epw_file_model.file.path
            epw_data = EPW(epw_file_path)

            monthly_averages = []
            monthly_mins = []
            monthly_maxs = []

            #HourlyContinuousCollection from epw file
            dry_bulb_temp = epw_data.dry_bulb_temperature
            print(dry_bulb_temp)

            #monthly_averages = dry_bulb_temp.average_monthly()
            grouped = dry_bulb_temp.group_by_month()

            for month, temps in grouped.items():
                monthly_averages.append(np.mean(temps))
                monthly_mins.append(np.min(temps))
                monthly_maxs.append(np.max(temps))

            # Ensure using the non-GUI backend for matplotlib
            matplotlib.use('Agg')

            # Set the Seaborn theme for nicer aesthetics
            sns.set_theme()

            # Generate a list of months (assuming 1 to 12 for simplicity)
            months = list(range(1, 13))

            # Plotting
            plt.figure(figsize=(10, 6))

            # Use fill_between to show the range between monthly minimum and maximum temperatures
            plt.fill_between(months, monthly_mins, monthly_maxs, color='lightblue', alpha=0.4, label='Min-Max Range')

            # Plot the monthly averages
            plt.plot(months, monthly_averages, label='Monthly Average', color='red', marker='o', linestyle='-')

            # Adding labels and title
            plt.xticks(months, ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])
            plt.xlabel('Month')
            plt.ylabel('Temperature (°C)')
            plt.title('Monthly Temperature Statistics')
            plt.legend()

            plt.tight_layout()

            # Save the plot to a BytesIO buffer
            buf = BytesIO()
            plt.savefig(buf, format='png', bbox_inches='tight')
            plt.close()
            buf.seek(0)

            # Encode the image to base64 string and decode to UTF-8
            image_base64 = base64.b64encode(buf.getvalue()).decode('utf-8')
            buf.close()

            # Update context with form, analysis results, and the plot image
            context.update({
                'image_base64': image_base64,
            })
        except EPWFile.DoesNotExist:
            context['message'] = 'EPW file not found. Please upload a file.'
    else:
        context['message'] = 'Please upload an EPW file to view weather statistics.'

    return render(request, 'firstapp/weatherstats.html', context)

def pv_tool(request):
    form = PVToolForm(request.POST or None)
    context = {'form': form, 'active_page': 'pv_tool'}

    chart = None  # Initialize chart variable
    
    if request.method == 'POST' and form.is_valid():
        
        epw_file_id = request.session.get('epw_file_id')
        epw_file_model = EPWFile.objects.get(id=epw_file_id)
        epw_file_path = epw_file_model.file.path
        epw_data = EPW(epw_file_path)

        width = form.cleaned_data['roof_width']
        length = form.cleaned_data['roof_length']
        pv_width = form.cleaned_data['pv_width']
        pv_height = form.cleaned_data['pv_height']
        height = 3.2
        h_seperation = 0.1
        v_seperation = 2.5

        # Create room and shade
        room = Room.from_box('test1', width, length, 3.2)  # Example height of 3.2
        v_offset = 0.05

        pv_array = []
        copy_d = pv_width+h_seperation
        rx = []

        axis_test = Vector3D(1,0,0)
        n_max = int(np.floor((width + h_seperation)/(pv_width + h_seperation))) #calculate max panels fitting horizontally

        for i in range(n_max):
            if i == 0:
                rx.append([
                [0, 0, height+v_offset],           # Bottom-left corner
                [pv_width, 0, height+v_offset],       # Bottom-right corner
                [pv_width, pv_height, height+v_offset],  # Top-right corner
                [0, pv_height, height+v_offset]       # Top-left corner
                ])
                
            else:
                rx.append([
            [copy_d*(i), 0, height+v_offset],           # Bottom-left corner
            [pv_width+(copy_d*(i)), 0, height+v_offset],       # Bottom-right corner
            [pv_width+(copy_d*(i)), pv_height, height+v_offset],  # Top-right corner
            [copy_d*(i), pv_height, height+v_offset]       # Top-left corner
            ])
       
            origin_start = Point3D(0,0,rx[i][0][2])
            x = Shade.from_vertices(str(i),vertices=rx[i])
            x.rotate(axis=axis_test,angle=20, origin=origin_start)
            
            pv_array.append(x)

        ry = []
        y_max = int(np.floor(length/v_seperation)) #calculate max panels fitting horizontally

        count = len(pv_array) + 1
        for k in range(y_max):
            for i in pv_array:
                p = i.vertices
                y = Shade.from_vertices(str(count), p)
                y.move(Vector3D(0,v_seperation*int(k),0))
                ry.append(y)
                count += 1

        for i in ry:
            pv_array.append(i)

        shades = []
        for pv in pv_array:
            shades.append(pv.duplicate())
            if math.degrees(Vector3D(0, 0, 1).angle(pv.normal)) - 90 > 1:
                msg = 'Shade "{}" is pointing downwards, which is atypical of photovoltaics.\n' \
                    'You will likely want to flip the geometry to have it point upwards to ' \
                    'the sky.'.format(pv.display_name)
                print(msg)
            
        # create the base PV properties
        display_name = 'Photovoltaic Array {}'.format(len(shades))
        print(display_name)
        pv_id = clean_ep_string(display_name)
        pv_props = PVProperties(pv_id)
        pv_props.display_name = pv_id
        for shade in shades:
            shade.properties.energy.pv_properties = pv_props


        print('------')
        #print(pv_array)
        model = Model('test1', rooms=[room], orphaned_shades=shades)
         # process the simulation parameters
        
        sim_par = SimulationParameter()
        sim_par.output.add_zone_energy_use()
        sim_par.output.add_hvac_energy_use()
        sim_par.output.add_electricity_generation()
       
        #sim_par = sim_par.duplicate()  # ensure input is not edited

        simfolder_path = os.path.join(settings.MEDIA_ROOT, 'simulations')
        clean_name = re.sub(r'[^.A-Za-z0-9_-]', '_', model.display_name)
        directory = os.path.join(simfolder_path, clean_name, 'openstudio')

        model = model.duplicate()
        model.properties.energy.remove_hvac_from_no_setpoints()
         # auto-assign stories if there are none since most OpenStudio measures need these

dashboard/firstapp/templates/firstapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dashboard{% endblock title %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'home' %}">Dashboard</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item {% if active_page == 'home' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'home' %}">Home</a>
                    </li>
                    <li class="nav-item {% if active_page == 'weather_stats' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'weather_stats' %}">Weather</a>
                    </li>
                    <li class="nav-item {% if active_page == 'pv_tool' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'pv_tool' %}">Solar PV</a>
                    </li>
                    <li class="nav-item {% if active_page == 'energy_sim' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'energy_sim' %}">Energy Simulation</a>
                    </li>
                    <li class="nav-item {% if active_page == 'rainwater' %}active{% endif %}">
                        <a class="nav-link" href="{% url 'rainwater' %}">Rain Water Harvesting</a>
                    </li>
                    
                </ul>
            </div>
        </nav>

        

        <!-- EPW File Info Widget -->
        {% if request.session.epw_file_id and request.session.epw_file_name %}
        <div class="container-fluid">
            <div class="row align-items-start">
                <div class="col-12">
                    <!-- Adjusted styles for positioning and border -->
                    <div class="epw-info-widget" style="position: absolute; top: 60px; right: 20px; border: 1px solid #dee2e6; padding: 15px; border-radius: 5px;">
                        <h5>Weather File</h5>
                        <p>Location: {{ request.session.epw_file_location }}</p>
                        <p>Lat: {{ request.session.epw_file_lat }}, Long: {{ request.session.epw_file_long }}</p>
                        <button id="changeEpwBtn" type="button" class="btn btn-primary" onclick="confirmChange()">Change EPW File</button>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>


    <div class="container">
        {% block content %}
        {% endblock content %}
    </div>

    <script>
        function confirmChange() {
            const confirmChange = confirm("Are you sure you want to change the EPW file? All outputs will be reset.");
            if (confirmChange) {
                window.location.href = "{% url 'reset_epw' %}";
            }
        }
        </script>
        
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

dashboard/firstapp/templates/firstapp/energysim.html
{% extends 'firstapp/base.html' %}

{% block content %}
<h2>Run Energy Simulation in the Web</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload EPW File</button>
</form>

{% if dbt %}
    <h3>Model Inputs</h3>
{% endif %}
{% if visualization_url %}
    <h3>Energy Simulation Visualization</h3>
    <iframe src="{{ visualization_url }}" width="100%" height="600" style="border: none;"></iframe>
    <!-- Or as a direct link -->
    <a href="{{ visualization_url }}" target="_blank">View Visualization</a>
{% endif %}


{% endblock %}

dashboard/firstapp/templates/firstapp/home.html
{% extends 'firstapp/base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
<div class="text-center mt-5">
    <h1>Home Page</h1>
    <p>Upload an EPW file to get started.</p>
    <form method="post" enctype="multipart/form-data" id="uploadForm">
        {% csrf_token %}
        <div style="height:0; overflow:hidden;">
            {{ form.file }}
        </div>
        <!-- Ensure the button is centered by using a container div with text-center class -->
        <div class="text-center">
            <button type="button" class="btn btn-primary" id="uploadBtn">Upload EPW File</button>
        </div>
    </form>
</div>

<script>
    document.getElementById('uploadBtn').onclick = function() {
        var fileInput = document.getElementById('id_file');
        if (fileInput.files.length > 0) {
            // If a file is already selected, submit the form
            document.getElementById('uploadForm').submit();
        } else {
            // Trigger file selection dialog
            fileInput.click();
        }
    };

    // Trigger form submission after file is selected
    document.getElementById('id_file').onchange = function() {
        document.getElementById('uploadForm').submit();
    };
</script>
{% endblock %} 

dashboard/firstapp/templates/firstapp/rainwater.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="initial-scale=1, width=device-width" />

    <link rel="stylesheet" href="{% static 'css/global.css' %}">
    <link rel="stylesheet" href="{% static 'css/water-page.css' %}">
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Open Sans:wght@400;700;800&display=swap"
    />
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;900&display=swap"
    />
  </head>
  <body>
    <div class="water-page">
      <header class="nav1">
        <div class="rectangle3"></div>
        <div class="landie2">Dashboard</div>
        <div class="home-wrapper">
          <div class="home2">Home</div>
        </div>
        <div class="about-wrapper">
          <div class="about2">Solar PV</div>
        </div>
        <div class="contact-container">
          <div class="contact2">Water</div>
        </div>
      </header>
      <main class="content-main1">
        <div class="background1"></div>
        <div class="content-main-item"></div>
        <section class="frame-section">
          <div class="frame-parent2">
            <div class="frame-wrapper1">
              <div class="rainwater-harvesting-calculato-parent">
                <h2 class="rainwater-harvesting-calculato-container">
                  <p class="rainwater-harvesting-calculato">
                    Rainwater harvesting calculator
                  </p>
                </h2>
                <div class="this-rainwater-harvesting-calc-wrapper">
                  <div class="this-rainwater-harvesting">
                    This rainwater harvesting calculator estimates your
                    collection capacity using local weather data. Input your
                    catchment area to see monthly and annual projections, and
                    compare them with your building's water demand to calculate
                    your savings.
                  </div>
                </div>
              </div>
            </div>
            
            <form method="post">
                {% csrf_token %}
                <div class="length-catchment-area">
                    <div class="frame-parent3">
                        <div class="width-wrapper">
                            <div class="width1">Width</div>
                        </div>
                        <div class="length1">Length</div>
                        <div class="catchment-area-m21">Catchment area (m²)</div>
                    </div>
                      
                <div class="length-catchment-area-inner">
                    <div class="frame-parent4">
                    <div class="collection-container">                       
                            {{ form.width }}                      
                        <button class="frame-button">
                        <div class="frame-child1"></div>
                        <div class="group-div">
                            <div class="frame-child2"></div>
                            <div class="calculate1">Calculate</div>
                        </div>
                        </button>
                    </div>
                    <div class="x-container">
                        <div class="x1">X</div>
                    </div>
                    <div class="collection-container1">                        
                            {{ form.length }}    
                    </div>
                    <div class="frame">
                        <div class="div5">=</div>
                    </div>
                        {{ form.catchment_area }}    
                    </div>
                </div>
                </div>
                </form>
          </div>
          <img
            class="image-2-icon1"
            loading="lazy"
            alt=""
            src="{% static 'images/image-2@2x.png' %}"
          />
        </section>
        <section class="seperator-parent">
          <div class="seperator1"></div>
          <div class="frame-parent5" style="{% if not form_submitted %}display: none;{% endif %}">
            <div class="frame-wrapper2">
              <div class="frame-parent6">
                <div class="water-demand-wrapper">
                  <div class="water-demand hidden">Water demand</div>
                </div>
                <div class="collection-and-calculate-label-parent">
                  <div class="collection-and-calculate-label">
                    <b class="number-of-occupants2">Number of occupants</b>
                  </div>                  
                    <input type="number" class="input-class" min=1 value=1 id="num_people" name="num_people" placeholder="Enter value...">  
                </div>
                <div class="daily-cons1">
                  <div class="daily-cons-item"></div>
                  <div class="daily-consumption2">
                    <p class="daily-consumption3">Daily consumption</p>
                    <p class="blank-line2">&nbsp;</p>
                  </div>
                  <div class="daily-consumption-label-parent">
                    <div class="daily-consumption-label">50</div>
                    <div class="lday">L/day</div>
                  </div>
                </div>
              </div>
            </div>
            <div class="frame-wrapper3">
              <div class="frame-parent7">
                <div class="rectangle-parent1">
                  <div class="frame-child3"></div>
                  <div class="annual-rainwater-collection-container">
                    <p class="annual-rainwater-collection">
                      Annual rainwater collection
                    </p>
                    <p class="blank-line3">&nbsp;</p>
                    <p class="blank-line4">&nbsp;</p>
                  </div>
                </div>
                <img
                  class="image-3-icon1"
                  loading="lazy"
                  alt=""
                  src= {% static 'images/image-3@2x.png' %}
                />
              </div>
            </div>
            <div class="calculate-button-parent">
              <div class="calculate-button1">
                <div class="rectangle-parent2">
                  <div class="frame-child4"></div>
                  <div class="annual-summary-statistics2">
                    Annual Summary Statistics
                  </div>
                </div>
              </div>
              <div class="frame-wrapper4">
                <div class="collection-parent1">
                  <div class="collection9">
                    <div class="collection-child8"></div>
                    <div class="collection10">Collection</div>
                    <div class="collection-inner1">
                      <div class="parent2">
                        <div class="div6">{{ annual_storage }}</div>
                        <div class="savings-display">
                          <div class="m3">m<sup>3</sup></div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="consumption2">
                    <div class="consumption-item"></div>
                    <div class="consumption3">Consumption</div>
                    <div class="parent3">
                      <div class="div7">18.3</div>
                      <div class="savings-display1">
                        <div class="m31">m<sup>3</sup></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="frame-parent8">
                <div class="rectangle-parent3">
                  <div class="frame-child5"></div>
                  <div class="savings2">
                    <p class="savings3">Savings</p>
                  </div>
                </div>
                <div class="m3-water-12-container">
                  <p class="m3-water">
                    <span class="span">{{ annual_storage }} </span>
                    <span>m<sup>3</sup> water</span>
                  </p>
                  <p class="blank-line5">&nbsp;</p>
                  <p class="kgco22">
                    <span>1.2 </span>
                    <span class="kgco23">kgCO2</span>
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <div class="footer1">
        <div class="rectangle4"></div>
        <div class="parent4">
          <div class="div8">©2023 Yourcompany</div>
          <div class="landie3">Landing</div>
        </div>
        <footer class="rectangle-parent4">
          <div class="rectangle5"></div>
          <div class="frame-parent9">
            <div class="home-group">
              <div class="home3">Home</div>
              <div class="about3">About</div>
              <div class="contact3">Contact</div>
            </div>
            <div class="instagram-icon">
              <img
                class="iconsocialinstagram1"
                loading="lazy"
                alt=""
                src={% static 'images/iconsocialinstagram@2x.png' %}
              />
            </div>
          </div>
        </footer>
      </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            // Function to calculate the catchment area
            function calculateArea() {
                var width = parseFloat($('#id_width').val()); // Parse the width value to a number
                var length = parseFloat($('#id_length').val()); // Parse the length value to a number
                if (!isNaN(width) && !isNaN(length)) { // Check if both width and length are numbers
                    var area = width * length;
                    $('#id_catchment_area').val(area.toFixed(2)); // Update the area input with the calculated value
                }
            }

            function calculateConsumption() {
                var numPeople = parseFloat($('#num_people').val());
                if (!isNaN(numPeople)) {
                    // Assuming 50L per person per day
                    var dailyConsumption = numPeople * 50;
                    var annualConsumption = (dailyConsumption * 365)/1000; // Calculate annual consumption
        
                    // Update the DOM with the new values
                    $('.daily-consumption-label').text(dailyConsumption.toFixed(0));
                    // Assuming you have a .annual-consumption-label for showing the annual consumption
                    $('.div7').text(annualConsumption.toFixed(1));
                }
            }
        
            // Event listener for input on the width and length fields
            $('#id_width, #id_length').on('input', function() {
                // Check if the area field is empty or not
                if (!$('#id_catchment_area').val()) {
                    calculateArea();
                }
            });
        
            // If the area field is manually changed, remove the auto-calculation
            $('#id_catchment_area').on('input', function() {
                if ($(this).val()) {
                    // Remove the event listener if the area is manually entered
                    $('#id_width, #id_length').off('input', calculateArea);
                } else {
                    // Reattach the event listener if the area is cleared
                    $('#id_width, #id_length').on('input', calculateArea);
                }
            });

            // Event listener for input on the number of people field
            $('#num_people').on('input', function() {
                calculateConsumption();
            });

        });
    </script>
  </body>
</html>

dashboard/firstapp/templates/firstapp/weatherstats.html
{% extends 'firstapp/base.html' %}

{% block content %}


{% if image_base64 %}
    <h3>Daily Temperature Analysis</h3>
    <img src="data:image/png;base64,{{ image_base64 }}" alt="Daily Temperature Ranges and Averages">
{% else %}
    <p>{{ message }}</p>
{% endif %}

{% endblock %}